### ISSUE TITLE
magit diffs a bit hard on my eyes

### ISSUE THREAD

**Issue by mjhoy** [emacsfodder/emacs-boron-theme#1]
Hi,
first of all, love the theme. I've mostly switched to boron from tomorrow night, my previous favorite.

I found the colors in magit diffs rather hard to read. possibly my terminal is boosting the saturation a bit. I've toned things down here: https://github.com/mjhoy/emacs-boron-theme/commit/df17ed7f9640e0d7c18126feff6012a1ac8fe485

If you want I can submit a pull request.

**Comment by jasonm23** [comment]
Hi Michael, looks good.

A PR would be appreciated, thanks.
